export {default as Bookmarks} from './bookmarks/Bookmarks'
export {default as Explore} from './explore/Explore'
export {default as Trending} from './explore/Trending'
export {default as TrendingPosts} from './explore/TrendingPosts'
export {default as Home} from './home/Home'
export {default as LandingPage} from './landing-page/LandingPage'
export {default as Messages} from './messages/Messages'
export {default as Profile} from './profile/Profile'
export {default as ProfileInfo} from './profile/profile-info/ProfileInfo'
export {default as ProfileMetadata} from './profile/profile-info/ProfileMetadata'
export {default as ProfileMedia} from './profile/profile-info/ProfileMedia'
export {default as ProfileData} from './profile/profile-info/ProfileData'
export {default as ProfileSettings} from './profile/profile-info/ProfileSettings'
export {default as ToggleFollow} from './profile/ToggleFollow'
export {default as MediaSlideModal} from './profile/profile-info/MediaSlideModal'
export {default as UploadCoverPhoto} from './profile/profile-info/UploadCoverPhoto'
export {default as UploadPhoto} from './profile/profile-info/UploadPhoto'
// export {default as } from '.'